// SPDX-License-Identifier: MIT
// Code generated by Tygo v0.2.21 from sdk/go/protocol/types.go; DO NOT EDIT.
// Regenerate: npm run generate:types --prefix bus

export interface ExtraArgument {
  name: string;
  description: string;
  takes_value: boolean;
}
export type Integer = number /* int */;
export interface HelloDescription {
  supports_message_run?: boolean;
  product: string;
  version?: string;
  supported_open_fields: string[];
  extra_arguments: ExtraArgument[];
}
export interface WorkerHello extends HelloDescription {
  protocol: Integer;
  launch_token: string;
}
/**
 * PeerHello is a complete identity assertion; an empty Name omits the native name.
 */
export interface PeerHello {
  protocol: Integer;
  product: string;
  session_id: string;
  name?: string;
  groups: string[];
  info: { [key: string]: unknown};
}
export interface OpenOptions {
  cwd?: string;
  permission_mode?: string;
  model?: string;
  reasoning_effort?: string;
  arguments?: string[];
}
export interface LanePolicy {
  persistent: boolean;
  auto_close_ms: number /* int64 */;
  notify: boolean;
  notify_target?: string;
  owner_session_id?: string;
  /**
   * Trace is the live mode reported only in the spawning parent's response.
   * Absence means unreported, not off; it is never durable lane policy.
   */
  trace?: string;
}
export interface RunRef {
  session_id: string;
  run_id: string;
}
export interface ReadRequest {
  session_id: string;
  run_id?: string;
}
export interface WaitRequest {
  session_id: string;
  run_id?: string;
  timeout_ms?: number /* int64 */;
}
export interface RunStatus {
  session_id: string;
  run_id: string;
  state: string;
  result?: TurnResult;
  reason?: string;
}
export interface ExecuteRequest {
  session_id: string;
  run_id: string;
  input: string;
}
export interface TurnReady {
  session_id: string;
  run_id: string;
  state: string;
  outcome?: string;
  reason?: string;
}
export interface OpenRequest {
  policy?: LanePolicy;
  name: string;
  groups: string[];
  resume_session_id?: string;
  open: OpenOptions;
}
export interface OpenResult {
  session_id: string;
}
export interface TurnRunRequest {
  session_id: string;
  input: string;
}
export interface TurnResult {
  outcome: string;
  result: string;
  truncated?: boolean;
  native_stop_reason?: string;
}
export interface DeliverySource {
  session_id: string;
  name?: string;
  product: string;
  groups: string[];
}
export interface DeliveryRequest {
  run_id?: string;
  message_id: string;
  from: DeliverySource;
  body: string;
}
export interface DeliveryReceipt {
  disposition: string;
  reason?: string;
}
export interface HostProducts {
  host: string;
  products: string[];
}
export interface SessionSummary {
  policy?: LanePolicy;
  session_id: string;
  kind: string;
  product: string;
  name?: string;
  groups: string[];
  connected: boolean;
  running: boolean;
  info?: { [key: string]: unknown};
}
export interface SessionListRequest {
  session_id?: string;
  host?: string;
}
export interface SessionListResult {
  /**
   * SelfInfo is the originating caller, independent of list filters. Older
   * daemons may omit it; never infer self from a session name or list order.
   */
  self_info?: SessionSelfInfo;
  sessions: SessionSummary[];
  hosts?: HostProducts[];
}
/**
 * SessionSelfInfo uses the same public identity fields as a message source.
 * It excludes connection credentials, owner tokens and transport metadata.
 */
export type SessionSelfInfo = DeliverySource;
export interface MessageSendRequest {
  target?: string;
  targets?: string[];
  group?: string;
  host?: string;
  message: string;
}
export interface MessageSendDelivery {
  target: string;
  session_id?: string;
  delivery_id?: string;
  disposition: string;
  reason?: string;
}
export interface MessageSendResult {
  message_id: string;
  deliveries: MessageSendDelivery[];
}
export interface LaneDescribeRequest {
  product: string;
  host?: string;
}
export type LaneDescribeResult = HelloDescription;
export interface LaneSpawnRequest {
  persistent?: boolean;
  auto_close_ms?: number /* int64 */;
  notify?: boolean;
  notify_target?: string;
  name?: string;
  product?: string;
  host?: string;
  resume_session_id?: string;
  extra_groups?: string[];
  open?: OpenOptions;
  trace?: string;
}
export interface LaneSpawnResult {
  policy?: LanePolicy;
  session_id: string;
}
export interface TraceConfigureRequest {
  session_id: string;
  mode: string;
}
export interface TraceConfigureResult {
  session_id: string;
  mode: string;
}
export interface SessionTarget {
  session_id: string;
}
export interface SessionCloseRequest {
  session_id: string;
  forget?: boolean;
}
export interface SpawnFailedData {
  exit_code?: number /* int */;
  stderr_tail: string[];
}
export interface RPCError {
  code: number /* int */;
  message: string;
  data?: unknown;
}
